# Generated by Django 6.1.1 on 2026-09-16 09:50

import thrill_frame_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Назва (для адмінки)"
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        help_text="Підтримуються посилання youtube.com, youtu.be або чистий ID",
                        max_length=255,
                        validators=[thrill_frame_app.models.validate_youtube_input],
                        verbose_name="YouTube Video ID або Посилання",
                    ),
                ),
                (
                    "overlay_text",
                    models.CharField(
                        max_length=255, verbose_name="Текст оверлею (знизу зліва)"
                    ),
                ),
                (
                    "show_brand",
                    models.BooleanField(
                        default=False, verbose_name="Показувати логотип Thrill Frame"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок відображення"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
            ],
            options={
                "verbose_name": "Відео слайд",
                "verbose_name_plural": "Відео слайди",
                "ordering": ["order"],
            },
        ),
    ]
