# Generated by Django 6.1.1 on 2026-09-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoslide",
            name="show_brand",
        ),
    ]
