# Generated by Django 6.1.1 on 2026-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0002_sitevisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Назва відео")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Наприклад: Music Video, Commercial",
                        max_length=100,
                        verbose_name="Категорія / Опис",
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        help_text="Наприклад: dQw4w9WgXcQ",
                        max_length=50,
                        verbose_name="YouTube Video ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортування"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Відображати на сайті"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Новинка",
                "verbose_name_plural": "Новинки",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
