# Generated by Django 6.1.1 on 2026-09-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0003_newrelease"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newrelease",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Новинка",
                "verbose_name_plural": "Новинки",
            },
        ),
        migrations.RemoveField(
            model_name="newrelease",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="newrelease",
            name="order",
        ),
        migrations.RemoveField(
            model_name="newrelease",
            name="youtube_id",
        ),
        migrations.AddField(
            model_name="newrelease",
            name="video_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Посилання на YouTube"
            ),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="category",
            field=models.CharField(max_length=100, verbose_name="Категорія"),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Заголовок"),
        ),
    ]
