# Generated by Django 6.1.1 on 2026-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "thrill_frame_app",
            "0004_alter_newrelease_options_remove_newrelease_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="newrelease",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
