# Generated by Django 6.1.1 on 2026-09-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0005_newrelease_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newrelease",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="video_url",
            field=models.URLField(verbose_name="Посилання на YouTube"),
        ),
    ]
