# Generated by Django 6.1.1 on 2026-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0006_alter_newrelease_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newrelease",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Новинка",
                "verbose_name_plural": "Новинки",
            },
        ),
        migrations.AddField(
            model_name="newrelease",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Менше число = вище у списку (0, 1, 2...)",
                verbose_name="Порядок сортування",
            ),
        ),
    ]
