# Generated by Django 6.1.1 on 2026-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0007_alter_newrelease_options_newrelease_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("instagram", "Instagram")],
                        default="telegram",
                        max_length=10,
                        verbose_name="Спосіб зв'язку",
                    ),
                ),
                (
                    "social_username",
                    models.CharField(max_length=100, verbose_name="Нікнейм"),
                ),
                ("message", models.TextField(verbose_name="Повідомлення")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
