# Generated by Django 6.1.1 on 2026-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0008_contactrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Назва")),
            ],
        ),
        migrations.CreateModel(
            name="VideoWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Назва")),
            ],
        ),
    ]
