# Generated by Django 6.1.1 on 2026-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0009_photosession_videowork"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="telegram_message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="ID повідомлення в Telegram"
            ),
        ),
    ]
