# Generated by Django 6.1.1 on 2026-09-21 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0010_contactrequest_telegram_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="videowork",
            name="video_url",
            field=models.URLField(
                default=datetime.datetime(
                    2026, 9, 21, 14, 16, 39, 509960, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Посилання на відео",
            ),
            preserve_default=False,
        ),
    ]
