# Generated by Django 6.1.1 on 2026-09-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0011_videowork_video_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videowork",
            options={
                "verbose_name": "Відеоробота",
                "verbose_name_plural": "Відеороботи",
            },
        ),
        migrations.AddField(
            model_name="videowork",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_videos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Вподобання",
            ),
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст коментаря")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="thrill_frame_app.videocomment",
                        verbose_name="Батьківський коментар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="thrill_frame_app.videowork",
                        verbose_name="Відео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коментар",
                "verbose_name_plural": "Коментарі",
                "ordering": ["-created_at"],
            },
        ),
    ]
