# Generated by Django 6.1.1 on 2026-09-22 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "thrill_frame_app",
            "0012_alter_videowork_options_videowork_likes_videocomment",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="videowork",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 9, 22, 12, 25, 36, 711235, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата створення",
            ),
            preserve_default=False,
        ),
    ]
