# Generated by Django 6.1.1 on 2026-09-23 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0013_videowork_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videowork",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Відеоробота",
                "verbose_name_plural": "Відеороботи",
            },
        ),
        migrations.AddField(
            model_name="photosession",
            name="cover_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Посилання на обкладинку"
            ),
        ),
        migrations.AddField(
            model_name="photosession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="photosession",
            name="drive_folder_url",
            field=models.URLField(
                default="", verbose_name="Посилання на папку Google Drive"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photosession",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_photos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="PhotoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Коментар")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="thrill_frame_app.photosession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
