# Generated by Django 6.1.1 on 2026-09-24 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "thrill_frame_app",
            "0014_alter_videowork_options_photosession_cover_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photocomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Фото - коментар",
                "verbose_name_plural": "Фото - коментарі",
            },
        ),
        migrations.AlterModelOptions(
            name="videocomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Відео - коментар",
                "verbose_name_plural": "Відео - коментарі",
            },
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="photo_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="thrill_frame_app.photosession",
                verbose_name="Фото сесія",
            ),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
