# Generated by Django 5.2.13 on 2026-09-24 15:59

import django.db.models.deletion
import thrill_frame_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thrill_frame_app", "0015_alter_photocomment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "contact request",
                "verbose_name_plural": "contact requests",
            },
        ),
        migrations.AlterModelOptions(
            name="newrelease",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "new release",
                "verbose_name_plural": "new releases",
            },
        ),
        migrations.AlterModelOptions(
            name="photocomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "photo comment",
                "verbose_name_plural": "photo comments",
            },
        ),
        migrations.AlterModelOptions(
            name="videocomment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "video comment",
                "verbose_name_plural": "video comments",
            },
        ),
        migrations.AlterModelOptions(
            name="videoslide",
            options={
                "ordering": ["order"],
                "verbose_name": "video slide",
                "verbose_name_plural": "video slides",
            },
        ),
        migrations.AlterModelOptions(
            name="videowork",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "video work",
                "verbose_name_plural": "video works",
            },
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="contact_method",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("instagram", "Instagram")],
                default="telegram",
                max_length=10,
                verbose_name="Contact method",
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="social_username",
            field=models.CharField(max_length=100, verbose_name="Social username"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="telegram_message_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram message ID"
            ),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="category",
            field=models.CharField(max_length=100, verbose_name="Category"),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first (0, 1, 2...)",
                verbose_name="Sort order",
            ),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="newrelease",
            name="video_url",
            field=models.URLField(verbose_name="YouTube URL"),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="photo_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="thrill_frame_app.photosession",
                verbose_name="Photo session",
            ),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="text",
            field=models.TextField(verbose_name="Comment"),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="photosession",
            name="cover_url",
            field=models.URLField(blank=True, null=True, verbose_name="Cover URL"),
        ),
        migrations.AlterField(
            model_name="photosession",
            name="drive_folder_url",
            field=models.URLField(verbose_name="Google Drive folder URL"),
        ),
        migrations.AlterField(
            model_name="photosession",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="videocomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="videocomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="thrill_frame_app.videocomment",
                verbose_name="Parent comment",
            ),
        ),
        migrations.AlterField(
            model_name="videocomment",
            name="text",
            field=models.TextField(verbose_name="Comment text"),
        ),
        migrations.AlterField(
            model_name="videocomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="videocomment",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="thrill_frame_app.videowork",
                verbose_name="Video",
            ),
        ),
        migrations.AlterField(
            model_name="videoslide",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="videoslide",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Display order"),
        ),
        migrations.AlterField(
            model_name="videoslide",
            name="overlay_text",
            field=models.CharField(
                max_length=255, verbose_name="Overlay text (bottom left)"
            ),
        ),
        migrations.AlterField(
            model_name="videoslide",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title (for admin)"),
        ),
        migrations.AlterField(
            model_name="videoslide",
            name="youtube_id",
            field=models.CharField(
                help_text="Supports youtube.com, youtu.be, or a plain ID",
                max_length=255,
                validators=[thrill_frame_app.models.validate_youtube_input],
                verbose_name="YouTube video ID or URL",
            ),
        ),
        migrations.AlterField(
            model_name="videowork",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="videowork",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_videos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Likes",
            ),
        ),
        migrations.AlterField(
            model_name="videowork",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="videowork",
            name="video_url",
            field=models.URLField(verbose_name="Video URL"),
        ),
    ]
